### ISSUE TITLE
create descriptions for FTIR components

### ISSUE THREAD

**Issue by VanFossen** [RastonLab/Virtual-FTIR-Spectrometer#25]

**Comment by spectroscopy** [comment]
Can't figure out how to do superscript/subscript so here's a word doc:
[FTIR_notes_0.docx](https://github.com/RastonLab/Virtual-FTIR-Spectrometer/files/9123304/FTIR_notes_0.docx)

**Comment by VanFossen** [comment]
All good! Here is an example of superscript/subscript if interested:

`CO<sub>2</sub>` --> CO<sub>2</sub>

`3.14 * 10<sup>6</sup>` --> 3.14 * 10<sup>6</sup>
