### ISSUE TITLE
Update animation times based on the updated FTIR.xlsx file

### ISSUE THREAD

**Issue by Brennaser** [RastonLab/Virtual-FTIR-Spectrometer#265]
Original file from Dr. Raston

[FTIR.xlsx](https://github.com/RastonLab/Virtual-FTIR-Spectrometer/files/12283149/FTIR.xlsx)

**Comment by VanFossen** [comment]
Updated file from Dr. Raston

[FTIR_v1.xlsx](https://github.com/RastonLab/Virtual-FTIR-Spectrometer/files/12283120/FTIR_v1.xlsx)
