### ISSUE TITLE
Update Landing Page

### ISSUE THREAD

**Issue by Brennaser** [RastonLab/Virtual-FTIR-Spectrometer#266]
Currently the Landing Page (the page with `Welcome to FTIR-SIS`) is somewhat underutilized. Possibly utilize a popup on the first load of the page with that information.

- Dr. Raston liked the idea of replacing this page with a popup upon first visit
> Perhaps we could say something like "If you are new to the application we recommend you goto the instrument window" and include a link that takes them there

**Comment by VanFossen** [comment]
This could be done by utilizing `localStorage` (client side storage): https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage
