### ISSUE TITLE
FTIR backend: Calculate spectra

### ISSUE THREAD

**Issue by spectroscopy** [RastonLab/Virtual-FTIR-Spectrometer#3]
For the backend the plan is to use RADIS: https://github.com/radis/radis. It will simulate infrared spectra given a bunch of parameters. I'm unsure of the best way of doing this, but I notice there is an app (https://github.com/suzil/radis-app) that already has a decent (but incomplete) interface; I hope we can use the "radis-app" code as a starting point. Perhaps the 1st task should be to get this code working so we can customize it. What were initially after is a transmission spectrum of a gas sample, lets say of CO (ie carbon monoxide; that can be the test molecule).

Next we need to process this transmission spectrum to make it appear as though it has been collected with a real spectrometer (im calling this processed spectrum the "virtual spectrum"). To do that we need to multiply the transmission spectrum of the gas sample by the blackbody spectrum of the source, the transmission spectrum of the beamsplitter material and windows, and the detector response spectrum. The detector response spectra will contain noise (which will slowly go away in the virtual spectrum with scanning time). Here's the formula we use: virtual spectrum = (a) transmission spectrum of gas sample x (b) blackbody spectrum of source x (c) transmission spectrum of windows/beamsplitter x (d) detector response spectrum. Breaking this down:

(a) transmission spectrum of gas sample is generated using radis-app (?)

(b) blackbody spectrum of source: We will use Planck's law to do this. The associated spectrum is called a Planck spectrum. The user can choose one of two sources (of light): (i) Globar (which has a temperature of 1700 K); and (ii) Tungsten (3100 K). This page should be helpful to generate blackbody spectra (see https://radis.readthedocs.io/en/latest/examples/examples.html#compute-blackbody-radiation-spectrum).

(c) transmission spectrum of windows/beamsplitter: There is 9 mm of window material the light passes through: 3 mm of beamsplitter, 2x2 mm of windows that are attached to the ends of the sample cell, and a 2 mm window on the detector. The beamsplitter will be AR-ZnSe or AR-CaF2 (depending on what the user chooses; the "AR" means the window has an AntiReflective coating; without "AR" it is assumed to be uncoated); the "2x2 mm of windows" will be KBr or CaF2; the "2 mm window on the detector" will be ZnSe if MCT detector is chosen and sapphire if InSb detector is chosen. Mathematical functions for the "transmission spectrum of windows/beamsplitter" were generated by fitting various mathematical functions to actual transmission spectra (note, col(a) = x):

KBr (2 mm):
(0.92267) / (1 + (25.66477/col(a))^-12.35159 )^0.17344
Valid from 0.3-30 um
x is wavelength in um (micrometers) and y is fractional transmission.
Note I fit the transmission spectrum in um for convenience.
![Image](https://user-images.githubusercontent.com/75122115/172240714-01b096d5-6e40-4437-8ad9-13dc48bcf240.png)

CaF2 (2 mm):
(0.93091) / (1 + (11.12929/col(a))^-12.43933 )^4.32574
Valid from 0.7-23.5 um
![Image](https://user-images.githubusercontent.com/75122115/172243307-cab29bc1-fffe-412d-a223-4d3910d1b141.png)

ZnSe (2 mm):
(0.71015) / (1 + (20.99353 /col(a))^-19.31355 )^1.44348+-0.13265/(2.25051*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-16.75)^2/2.25051^2)
Valid from 0.8-25 um
![Image](https://user-images.githubusercontent.com/75122115/172203476-6168ddf0-7944-4d16-bc96-03ac99b39ea1.png)

sapphire (2 mm):
(0.78928) / (1 + (11.9544/col(a))^-12.07226 )^6903.57039
Valid from 0.3-at least 8 um
![Image](https://user-images.githubusercontent.com/75122115/172242367-e1ccfacc-a99f-4d41-9e52-db6b69c0d64c.png)

AR-ZnSe (3 mm):
(0.82609) / (1 + (34.63971/col(a))^-8.56269 )^186.34792+-0.47/(0.55*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-1.47)^2/0.55^2)+-0.03456/(0.4*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-2.88)^2/0.4^2)+-0.009/(0.3*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-6.16)^2/0.3^2) +-0.09/(1*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-16.2)^2/1^2)+-0.08/(1*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-17.4)^2/1^2)+1.12/(8*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-9.5)^2/8^2)+0.11546/(2*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-4.9)^2/2^2)+0.21751/(2*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-2.6)^2/2^2)+-0.05/(0.07*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-0.8)^2/0.07^2);
Valid from 0.8-about 23 um
![Image](https://user-images.githubusercontent.com/75122115/172200669-5f231ef9-ff04-4b3a-9220-26309673055b.png)

AR-CaF2 (3 mm):
(0.9795) / (1 + (18.77617/col(a))^-6.94246 )^91.98745+-0.06/(0.08*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-0.76)^2/0.08^2)+-0.06/(0.2*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-1.06)^2/0.20^2)+-0.6/(3.0*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-4.85)^2/3.0^2) +-0.35/(1.0*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-9.40)^2/1.00^2)+0.05/(0.8*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-2.60)^2/0.8^2)+0.04/(0.5*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-7.75)^2/0.50^2)+-0.01/(0.6*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-6.55)^2/0.6^2)+0.01/(0.5*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-1.82)^2/0.5^2)
Valid from 0.8-about 23 um
![image](https://user-images.githubusercontent.com/75122115/172407798-449d73bb-d482-49c5-9e85-b273b8e88333.png)

(d) detector response spectrum: The user can choose between MCT and InSb detectors. As mentioned above, the MCT detector has a 2 mm thick ZnSe window and the InSb detector has a 2 mm Sapphire window. Once again, mathematical functions were fit to actual spectra (col(a) = x):

InSb:
1.97163E11*(1/(1+exp(-(col(a)-5.3939)/1.6624)))*(1-1/(1+exp(-(col(a)-5.3939)/0.11925))) + 3.3E10/(2.44977*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-5)^2/2.44977^2)
![Image](https://user-images.githubusercontent.com/75122115/172681736-302baee6-364e-4b4f-b062-df0571b3ed6e.png)

MCT:
1.98748E9+ 2.10252E10*(1/(1+exp(-(col(a)-20.15819)/5.73688)))*(1-1/(1+exp(-(col(a)-20.15819)/1.11659))) + 1.3E9/(2*sqrt(pi/(4*ln(2)))) * exp(-4*ln(2)*(col(a)-18.6)^2/2^2)
![image](https://user-images.githubusercontent.com/75122115/172412786-01ca8c7f-5aa7-4ceb-a5d6-db56364f7942.png)

Note that we need to make the detector response spectra realistic by adding white noise. The amount we add depends on how much ends up in the virtual spectrum. We want it to be noisy enough such that students need to do something like 10 min of averaging to get a decent (lowish signal-to-noise spectrum). This may be helpful: 
(https://radis.readthedocs.io/en/latest/auto_examples/plot_specutils_processing.html#sphx-glr-auto-examples-plot-specutils-processing-py)

PS: The range of the spectrometer will be 400-12500 cm-1. We should generate and process spectra in um (microns) then convert to cm-1 (the units the spectra will be displayed in). The conversion is: 1 cm-1 = 1/(1E4 um).

**Comment by hcientist** [comment]
so the # of scans will change D in the formula bc each successive scan will give different parameters to the whitenoise generation step (see last link above) that must be added to the D function prior to multiplying ABC product with D

**Comment by spectroscopy** [comment]
Quick update: After some discussion, we decided that the white noise should be added after multiplying the detector response spectrum by the rest (adding the noise should be done after steps A thru D so that a constant level is evident across the spectrum). In a bit more detail, the white noise that is added should be determined as follows: For n scans, add n white noise spectra together, then divide by n.
